bl-obthemes: cope with restoring to files which are symlinks (like tint2rc)

diff --git a/bin/bl-obthemes b/bin/bl-obthemes
--- a/bin/bl-obthemes
+++ b/bin/bl-obthemes
@@ -788,16 +788,17 @@ function saveFiles(){
 function saveFileAbs(){
     local src_file target_file target_dir
     src_file="$1"
-    target_file="$2"
-    target_dir="${target_file%/*}"
-    [[ $target_file = $CONFIGDIR/* ]] || {
-        echo "$0: Target is not inside $CONFIGDIR" >&2
-        return 1
-    }
+    [[ -L "$src_file" ]] && debug "$src_file is a symbolic link, pointing to $(readlink -f "$src_file")"
     [[ -r $src_file ]] || {
         echo "$0: Cannot read source file $src_file" >&2
         return 1
     }
+    target_file="$2"
+    [[ $target_file = $CONFIGDIR/* ]] || {
+        echo "$0: Target is not inside $CONFIGDIR" >&2
+        return 1
+    }
+    target_dir="${target_file%/*}"
     mkdir -p "$target_dir" || return 1
     if [[ -d $src_file ]];then
         cp -r "$src_file" "$target_file" || return 1
@@ -2158,9 +2159,15 @@ function copyDir(){
 # $1 and $2 are absolute source and target filepaths
 # BKP_SFX is global set by restoreSettings()()
 function restoreFileAbs(){
-    local src_file src_content tmpsrc target_file target_dir bkp_file extra_txt
+    local src_file src_content tmpsrc target_file target_file_canon target_dir bkp_file extra_txt
     src_file="$1"
     target_file="$2"
+    target_file_canon="$(readlink -f "$target_file")" # canonical path
+    [[ -L "$target_file" ]] && debug "$target_file is a symbolic link, pointing to $target_file_canon"
+    [[ -w "$target_file" ]] || {
+        echo "$0: Cannot restore $src_file because $target_file is not writable." >&2
+        return 1
+    }
     target_dir="${target_file%/*}"
     mkdir -p "$target_dir" || return 1
     extra_txt=''
@@ -2173,13 +2180,13 @@ function restoreFileAbs(){
     }
     if [[ -e $target_file ]];then        # backup config first
         diff -qBEbZ "$src_file" "$target_file" >/dev/null && {
-            debug "\n  $target_file and ${1}${extra_txt} are identical, no need to restore."
+            debug "\n  $target_file and ${src_file}${extra_txt} are identical, no need to restore."
             return 0
         }
         needBackup "${target_file}" && {
-            bkp_file="${target_file}${BKP_SFX}"
-            mv "$target_file" "$bkp_file" || return 1
-            debug "\n  $target_file backed up"
+            bkp_file="${target_file_canon}${BKP_SFX}"
+            cp "$target_file" "$bkp_file" || return 1
+            debug "\n  $target_file backed up to $bkp_file"
         }
         cp "$src_file" "$target_file" || return 1
         debug "\n  $target_file restored"
@@ -2196,9 +2203,10 @@ function restoreFileAbs(){
 # Return 1 if found (no backup needed before overwrite),
 # otherwise return 0 (do backup).
 needBackup(){
-    local file bkp_file path dir blobfile homefile_content blobfile_content
+    local file file_canon bkp_file path dir blobfile homefile_content blobfile_content
     file=$1
-    for bkp_file in "${file}"*~
+    file_canon="$(readlink -f "$file")" # canonical path if $file is symlink
+    for bkp_file in "${file_canon}"*~
     do
         [[ -f $bkp_file ]] || continue
         diff -qBEbZ "$file" "$bkp_file" >/dev/null && {
@@ -2403,6 +2411,8 @@ restoreSettings() {
             '('*')'         )   TAG="${TAG#(}" # "hidden" tags not added to labels, but may be used when restoring
                                 TAG="${TAG%)}"
                                 values["$TAG"]="$VAL"
+                                ;;
+            '')                 :
                                 ;;
             *               )   echo "$0: Ignoring unknown value: ${TAG} in $THEMEPATH/settings.cfg" >&2
                                 ;;
